# default config
# - run current firmware
# - do not write firmware to flash
# - do not attach gdb
# - attach rtt debug

[default.probe]
protocol = "Jtag"

[default.flashing]
enabled = false
halt_afterwards = false
restore_unwritten_bytes = false

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "GD32VF103CBT6"
log_level = "WARN"
connect_under_reset = false

[default.rtt]
enabled = true
channels = []
timeout = 3000
show_timestamps = true
log_enabled = false

[default.gdb]
enabled = false
gdb_connection_string = "127.0.0.1:1337"

# flash config
# - write firmware to flash
# - run written firmware
# - do not attach rtt debug

[flash.probe]
protocol = "Jtag"

[flash.rtt]
enabled = false

[flash.flashing]
enabled = true
halt_afterwards = false
restore_unwritten_bytes = false
